name: Menu Photo to Teams

on:
  push:
    branches:
      - main
    paths:
      - 'menuphotos/**'

jobs:
  post-menu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y tesseract-ocr

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run OCR & Post
        run: python menu_bot.py
